# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo/v1/locations.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("demo/v1/locations.proto", :syntax => :proto3) do
    add_message "demo.v1.Location" do
      optional :id, :int64, 1
      optional :warehouse_id, :int64, 2
      optional :code, :string, 3
      optional :address, :string, 4
    end
    add_message "demo.v1.GetLocationsRequest" do
      optional :warehouse_id, :int64, 1
    end
    add_message "demo.v1.GetLocationsResponse" do
      repeated :locations, :message, 1, "demo.v1.Location"
    end
  end
end

module Demo
  module V1
    Location = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.v1.Location").msgclass
    GetLocationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.v1.GetLocationsRequest").msgclass
    GetLocationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.v1.GetLocationsResponse").msgclass
  end
end
