# Code generated by protoc-gen-twirp_ruby 1.3.0, DO NOT EDIT.
require 'twirp'
require_relative 'locations_pb.rb'

module Demo
  module V1
    class LocationRetrievalService < Twirp::Service
      package 'demo.v1'
      service 'LocationRetrieval'
      rpc :GetLocations, GetLocationsRequest, GetLocationsResponse, :ruby_method => :get_locations
    end

    class LocationRetrievalClient < Twirp::Client
      client_for LocationRetrievalService
    end
  end
end
